import Head from "next/head";
import DataTable from "../components/table";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/icon?family=Material+Icons"
        />

        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <DataTable />
      </main>
    </>
  );
}
