import Head from "next/head";

type PageType = { children: JSX.Element; title?: string };

export default function Page({ children, title }: PageType) {
  return (
    <>
      <Head>
        <title>{title ?? "HortiFruit Brilhadori"}</title>
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/icon?family=Material+Icons"
        />

        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>{children}</main>
    </>
  );
}
